### ISSUE TITLE
Unable to find zpvector.hpp when building.

### ISSUE THREAD

**Issue by aleppard** [rookiepeng/radarsimpy#4]
Hello,

Thanks for making this code available.

I'm having trouble using the cython files. There are no installation instructions on how to build them into a library, so I've created a simple setup.py file (see below) to do this. However, when it tries to build it can't find the C++ header file "zpvector.hpp" referenced in zpvector.pxd:

```
cdef extern from "zpvector.hpp" namespace "zpv" nogil:
```

If I'm not mistaken it's looking for an external C++ header file dependency but I don't know which package provides this file. 

You mention this:

_This module needs to be built/used together with RadarSimC (the C++ engine for radar simulator)_

Is there an external C++ RadarSimC engine I need to install first? If so, where can I find that? Thanks.

For reference my setup file below:

```
from distutils.core import setup
from distutils.extension import Extension

from Cython.Build import cythonize
import numpy

source = [
    "lib/cp_radarsimc.pyx"
]

extensions = [
    Extension('radarsimc', source,
              include_dirs = [numpy.get_include()])
    ]

setup(
    ext_modules=cythonize(extensions)
)
```

**Comment by rookiepeng** [comment]
This is expected as the radarsimc is not available and it is not planned to be open sourced for now.

If you want to try the module, please send a message at the bottom of https://zpeng.me/
